// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw1HVtD3SF2rwOvrvEu4JwMYdZfoj-rPI',
    appId: '1:771129806808:web:3d340872fe594f64e3ecad',
    messagingSenderId: '771129806808',
    projectId: 'stashstash-99c0f',
    authDomain: 'stashstash-99c0f.firebaseapp.com',
    storageBucket: 'stashstash-99c0f.firebasestorage.app',
    measurementId: 'G-94K64JXY9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mCcyIIRpS1NZnemw73m_YiouL68Ye_g',
    appId: '1:771129806808:android:d5f0068f400c6aebe3ecad',
    messagingSenderId: '771129806808',
    projectId: 'stashstash-99c0f',
    storageBucket: 'stashstash-99c0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-XCkwQMhcgTEO-1Pp1LZm7lrxR-RVig',
    appId: '1:771129806808:ios:02bc26615dc1d789e3ecad',
    messagingSenderId: '771129806808',
    projectId: 'stashstash-99c0f',
    storageBucket: 'stashstash-99c0f.firebasestorage.app',
    iosBundleId: 'com.example.stashstash',
  );
}
